insert into public.cricket_games (
  id,
  game_date,
  season_label,
  competition,
  format,
  team,
  opponent,
  venue,
  result,
  runs,
  balls,
  wickets,
  overs,
  runs_conceded,
  catches,
  run_outs,
  distance_driven_miles,
  scorecard_url,
  story_slug,
  personal_note,
  source_status,
  is_archived
)
values
  (
    '1a0b55da-6f17-4de1-b7d8-950311698387',
    '2026-02-19',
    '2026',
    'TCL',
    'Leather ball',
    'TB Bengal Tigers',
    'Allies',
    'TCL ground',
    'Result not yet imported',
    2,
    3,
    0,
    0.0,
    0,
    2,
    0,
    null,
    null,
    null,
    'A light batting outing, but the kind of match remembered for staying switched on in the field and finishing with two catches.',
    'verified',
    false
  ),
  (
    '89c92d2f-1f7d-4b97-a0cb-cfb0feecfc66',
    '2026-01-25',
    '2026',
    'TB Bengal Tigers chapter',
    'Leather ball',
    'TB Bengal Tigers',
    'TBD from import',
    'To be added',
    'Awaiting full scorecard import',
    63,
    null,
    null,
    null,
    null,
    0,
    0,
    null,
    null,
    null,
    'The current headline innings in the archive. It is the kind of knock that deserves front-page space even before the full scorecard detail is attached.',
    'imported',
    false
  ),
  (
    '6faaf3b8-af36-447c-bbd7-4c74a0cf6dd0',
    '2025-08-10',
    '2025',
    'Titan Cup XI',
    'Leather ball',
    'SWAT',
    'TBD from import',
    'To be added',
    'Awaiting full scorecard import',
    54,
    null,
    null,
    null,
    null,
    0,
    0,
    null,
    null,
    null,
    'A reminder that some seasons are defined by the innings that arrive under pressure and hold the campaign together.',
    'imported',
    false
  ),
  (
    '90640880-72b9-4a39-9c50-16e2ee4f0602',
    '2024-11-02',
    '2024',
    'TPL 2024 Fall Series',
    'Tennis ball',
    'SWAT',
    'TBD from import',
    'To be added',
    'Awaiting full scorecard import',
    null,
    null,
    4,
    null,
    30,
    0,
    0,
    null,
    null,
    null,
    'The clearest bowling burst in the current archive and the best example of the all-round story being real, not just a label.',
    'imported',
    false
  ),
  (
    '4c2d8d7d-4b7f-4f77-aa53-c171634c0f1b',
    '2024-10-01',
    '2024',
    'League match',
    'Unknown',
    'SWAT',
    'Royal Phoenix',
    'To be added',
    'SWAT won by 3 runs',
    29,
    24,
    1,
    null,
    null,
    0,
    0,
    null,
    null,
    'seven-to-defend-swat-vs-royal-phoenix',
    'A 29 off 24 helped SWAT reach 95, but the memory is the final over: seven to defend, wides that nearly flipped the game, Amit Saha''s wicket at the key moment, and a dot ball to finish it.',
    'manually added',
    false
  ),
  (
    '52706b7c-ece7-4c1b-a770-4d433771f0f6',
    '2024-06-22',
    '2024',
    'Titan Cup X',
    'Leather ball',
    'St Pete Shields',
    'TBD from import',
    'To be added',
    'Awaiting full scorecard import',
    33,
    null,
    null,
    null,
    null,
    0,
    0,
    null,
    null,
    null,
    'A compact finishing or stabilizing innings entry held here until the full scorecard details arrive.',
    'imported',
    false
  ),
  (
    '74a77203-9c49-466a-a6db-4cad5cf37511',
    '2023-12-01',
    'Pre-archive',
    'Archive memory',
    'Unknown',
    'Bengals',
    'Add manually',
    'Add manually',
    'Manual memory entry',
    null,
    null,
    null,
    null,
    null,
    0,
    0,
    null,
    null,
    null,
    'Reserved for matches that matter before the scorecards are fully available: community games, remembered transitions, and the stories the raw data never captures on its own.',
    'manually added',
    false
  )
on conflict (id) do update
set
  game_date = excluded.game_date,
  season_label = excluded.season_label,
  competition = excluded.competition,
  format = excluded.format,
  team = excluded.team,
  opponent = excluded.opponent,
  venue = excluded.venue,
  result = excluded.result,
  runs = excluded.runs,
  balls = excluded.balls,
  wickets = excluded.wickets,
  overs = excluded.overs,
  runs_conceded = excluded.runs_conceded,
  catches = excluded.catches,
  run_outs = excluded.run_outs,
  distance_driven_miles = excluded.distance_driven_miles,
  scorecard_url = excluded.scorecard_url,
  story_slug = excluded.story_slug,
  personal_note = excluded.personal_note,
  source_status = excluded.source_status,
  is_archived = excluded.is_archived;
